version: '3'
services:
  server:
    build: ./server
    ports:
      - '4001:4001'
    container_name: webrtc_server
  client:
    build: ./client
    ports:
      - '4000:4000'
    depends_on:
      - server
    container_name: webrtc_client
