
version: '3.8'

services:
  client:
    build: ./client
    ports:
      - "4000:3000"
    volumes:
      - ./client:/app
    working_dir: /app
    command: npm run dev

  server:
    build: ./server
    ports:
      - "4001:4001"
    volumes:
      - ./server:/app
    working_dir: /app
    command: node index.js
